# ApproVideo Self-Hosted Cloud Stack
# Parse Server + Jitsi Meet + MediaGoblin + Etherpad + Frontend
version: '3.8'

services:
  # === CORE BACKEND SERVICES ===
  
  # 1. MongoDB Database
  mongo_db:
    image: mongo:6.0
    container_name: approvideo-mongo
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    networks:
      - backend
    # No ports exposed - only accessible internally

  # 2. Parse Server
  parse-server:
    image: parseplatform/parse-server:latest
    container_name: approvideo-parse
    restart: unless-stopped
    environment:
      - PARSE_SERVER_APPLICATION_ID=MY_LOCAL_APP_ID
      - PARSE_SERVER_MASTER_KEY=etiupereEREETertk5erretreJJ01@4@b
      - PARSE_SERVER_DATABASE_URI=mongodb://mongo_db:27017/parsedb_dev
      - PARSE_SERVER_URL=http://localhost:1337/parse
      - PARSE_SERVER_MOUNT_PATH=/parse
      - PARSE_SERVER_CLOUD=/parse-server/cloud/main.js
      - PARSE_SERVER_START_LIVE_QUERY_SERVER=true
      - PARSE_SERVER_ALLOW_CLIENT_CLASS_CREATION=true
      - PARSE_SERVER_SCHEMA_INIT_ON_START=true
      - PARSE_SERVER_ENABLE_ANONYMOUS_USERS=true
    volumes:
      - ./cloud:/parse-server/cloud
    depends_on:
      - mongo_db
    networks:
      - backend
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.parse.rule=Host(`api.approvideo.org`)"
      - "traefik.http.routers.parse.entrypoints=web,websecure"
      - "traefik.http.routers.parse.tls=true"
      - "traefik.http.services.parse.loadbalancer.server.port=1337"

  # === COLLABORATION SERVICES ===

  # 3a. Jitsi Prosody (XMPP Server)
  prosody:
    image: jitsi/prosody:stable
    container_name: approvideo-prosody
    restart: unless-stopped
    environment:
      - ENABLE_AUTH=0
      - ENABLE_GUESTS=1
      - XMPP_DOMAIN=meet.jitsi
      - XMPP_AUTH_DOMAIN=auth.meet.jitsi
      - XMPP_MUC_DOMAIN=muc.meet.jitsi
      - XMPP_INTERNAL_MUC_DOMAIN=internal-muc.meet.jitsi
      - JICOFO_COMPONENT_SECRET=s3cr37
      - JVB_COMPONENT_SECRET=s3cr37
      - JICOFO_AUTH_USER=focus
      - JICOFO_AUTH_PASSWORD=passw0rd
      - PUBLIC_URL=https://meet.approvideo.org
    networks:
      - web

  # 3b. Jitsi Conference Focus (jicofo)
  jicofo:
    image: jitsi/jicofo:stable
    container_name: approvideo-jicofo
    restart: unless-stopped
    environment:
      - XMPP_DOMAIN=meet.jitsi
      - XMPP_AUTH_DOMAIN=auth.meet.jitsi
      - XMPP_SERVER=prosody
      - JICOFO_COMPONENT_SECRET=s3cr37
      - JICOFO_AUTH_USER=focus
      - JICOFO_AUTH_PASSWORD=passw0rd
      - JVB_BREWERY_MUC=jvbbrewery
      - JICOFO_BRIDGE_MUC=jvbbrewery
    depends_on:
      - prosody
    networks:
      - web

  # 3c. Jitsi Video Bridge
  jvb:
    image: jitsi/jvb:stable
    container_name: approvideo-jvb
    restart: unless-stopped
    ports:
      - "10000:10000/udp"  # Video bridge UDP port
    environment:
      - XMPP_DOMAIN=meet.jitsi
      - XMPP_AUTH_DOMAIN=auth.meet.jitsi
      - XMPP_SERVER=prosody
      - JVB_COMPONENT_SECRET=s3cr37
      - JVB_BREWERY_MUC=jvbbrewery
      - JVB_PORT=10000
      - JVB_TCP_HARVESTER_DISABLED=true
      - JVB_WS_DOMAIN=meet.approvideo.org
      - JVB_WS_SERVER_ID=default-id
      - PUBLIC_URL=https://meet.approvideo.org
    depends_on:
      - prosody
    networks:
      - web

  # 3d. Jitsi Web Interface
  jitsi-web:
    image: jitsi/web:stable
    container_name: approvideo-jitsi
    restart: unless-stopped
    environment:
      - ENABLE_AUTH=0
      - ENABLE_GUESTS=1
      - ENABLE_RECORDING=0
      - XMPP_DOMAIN=meet.jitsi
      - XMPP_AUTH_DOMAIN=auth.meet.jitsi
      - XMPP_BOSH_URL_BASE=http://prosody:5280
      - XMPP_MUC_DOMAIN=muc.meet.jitsi
      - PUBLIC_URL=https://meet.approvideo.org
      - JICOFO_AUTH_USER=focus
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jitsi.rule=Host(`meet.approvideo.org`)"
      - "traefik.http.routers.jitsi.entrypoints=web,websecure"
      - "traefik.http.routers.jitsi.tls=true"
      - "traefik.http.services.jitsi.loadbalancer.server.port=80"
    depends_on:
      - prosody
      - jicofo
      - jvb
    networks:
      - web

  # 4. MediaGoblin (Media Storage)
  mediagoblin:
    image: mediagoblin/mediagoblin:0.14.0
    container_name: approvideo-media
    restart: unless-stopped
    volumes:
      - mediagoblin_data:/srv/mediagoblin/user_dev
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.media.rule=Host(`media.approvideo.org`)"
      - "traefik.http.routers.media.entrypoints=web,websecure"
      - "traefik.http.routers.media.tls=true"
      - "traefik.http.services.media.loadbalancer.server.port=80"
    networks:
      - web

  # 5. Etherpad (Collaborative Documents)
  etherpad:
    image: etherpad/etherpad
    container_name: approvideo-pad
    restart: unless-stopped
    environment:
      - TITLE=ApproVideo Shared Notes
      - DEFAULT_PAD_TEXT=Welcome to ApproVideo shared meeting notes! 📝
      - ADMIN_PASSWORD=changeme_secure_password
      - REQUIRE_SESSION=false
      - EDIT_ONLY=false
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.etherpad.rule=Host(`pad.approvideo.org`)"
      - "traefik.http.routers.etherpad.entrypoints=web,websecure"
      - "traefik.http.routers.etherpad.tls=true"
      - "traefik.http.services.etherpad.loadbalancer.server.port=9001"
    networks:
      - web

  # 6. Frontend Hub (Static Site)
  hub-frontend:
    image: nginx:alpine
    container_name: approvideo-hub
    restart: unless-stopped
    volumes:
      - ./frontend/hub.approvideo.org:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hub.rule=Host(`hub.approvideo.org`)"
      - "traefik.http.routers.hub.entrypoints=web,websecure"
      - "traefik.http.routers.hub.tls=true"
      - "traefik.http.services.hub.loadbalancer.server.port=80"
      # Add CORS headers for API access
      - "traefik.http.middlewares.cors.headers.accesscontrolallowmethods=GET,OPTIONS,PUT,POST,DELETE,PATCH"
      - "traefik.http.middlewares.cors.headers.accesscontrolalloworiginlist=*"
      - "traefik.http.middlewares.cors.headers.accesscontrolmaxage=100"
      - "traefik.http.middlewares.cors.headers.addvaryheader=true"
      - "traefik.http.routers.hub.middlewares=cors"
    networks:
      - web

  # === INFRASTRUCTURE ===

  # 7. Traefik Reverse Proxy & Load Balancer
  traefik:
    image: traefik:v2.10
    container_name: approvideo-traefik
    restart: unless-stopped
    ports:
      - "80:80"    # HTTP
      - "443:443"  # HTTPS
      - "8080:8080" # Traefik Dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - ./certs:/certs:ro
      - ./letsencrypt:/letsencrypt
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.approvideo.org`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.entrypoints=web,websecure"
      - "traefik.http.routers.traefik.tls=true"
    networks:
      - web

# === PERSISTENT DATA ===
volumes:
  mongo_data:
    driver: local
  mediagoblin_data:
    driver: local

# === NETWORKS ===
networks:
  web:
    driver: bridge
  backend:
    driver: bridge
    internal: true
